on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [edited]
  schedule:
    # every hour
    - cron: 0 * * * *

name: Renovate

jobs:
  check_dependencies:
    name: Check dependencies
    runs-on: ubuntu-20.04
    if: |
      (github.event_name != 'pull_request') || startsWith(github.head_ref, 'renovate/')
    steps:
      - uses: actions/checkout@v2

      - name: Renovate repository
        uses: netlify/renovate-cli-action@v1
        with:
          github-token: ${{ secrets.PKG_RELEASE_TOKEN }}
          git-author: "Renovate Bot <statusbot@netlify.com>"
